#!/bin/sh
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/access_log > eolinker_com_apinto_access_log.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/strategy-plugin-visit > eolinker_com_apinto_strategy-plugin-visit.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/strategy-plugin-data_mask > eolinker_com_apinto_strategy-plugin-data_mask.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/plugin_app > eolinker_com_apinto_plugin_app.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/monitor > eolinker_com_apinto_monitor.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/http_to_dubbo2 > eolinker_com_apinto_http_to_dubbo2.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/proxy_rewrite > eolinker_com_apinto_proxy_rewrite.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/proxy_rewrite_v2 > eolinker_com_apinto_proxy_rewrite_v2.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/dubbo2-proxy-rewrite > eolinker_com_apinto_dubbo2-proxy-rewrite.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/dubbo2_to_http > eolinker_com_apinto_dubbo2_to_http.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/request_interception > eolinker_com_apinto_request_interception.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/response_rewrite > eolinker_com_apinto_response_rewrite.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/js_inject > eolinker_com_apinto_js_inject.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/request_file_parse > eolinker_com_apinto_request_file_parse.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/rate_limiting > eolinker_com_apinto_rate_limiting.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/acl > eolinker_com_apinto_acl.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/prometheus > eolinker_com_apinto_prometheus.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/response_filter > eolinker_com_apinto_response_filter.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/grpc_to_http > eolinker_com_apinto_grpc_to_http.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/http-mocking > eolinker_com_apinto_http-mocking.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/ip_restriction > eolinker_com_apinto_ip_restriction.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/cors > eolinker_com_apinto_cors.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/strategy-plugin-limiting > eolinker_com_apinto_strategy-plugin-limiting.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/extra_params > eolinker_com_apinto_extra_params.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/access_relational > eolinker_com_apinto_access_relational.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/data_transform > eolinker_com_apinto_data_transform.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/counter > eolinker_com_apinto_counter.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/grpc-proxy_write > eolinker_com_apinto_grpc-proxy_write.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/gzip > eolinker_com_apinto_gzip.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/strategy-plugin-cache > eolinker_com_apinto_strategy-plugin-cache.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/extra_params_v2 > eolinker_com_apinto_extra_params_v2.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/response_rewrite_v2 > eolinker_com_apinto_response_rewrite_v2.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/params_check > eolinker_com_apinto_params_check.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/circuit_breaker > eolinker_com_apinto_circuit_breaker.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/rsa > eolinker_com_apinto_rsa.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/http_to_grpc > eolinker_com_apinto_http_to_grpc.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/body_check > eolinker_com_apinto_body_check.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/params_transformer > eolinker_com_apinto_params_transformer.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/proxy_mirror > eolinker_com_apinto_proxy_mirror.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/oauth2 > eolinker_com_apinto_oauth2.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/strategy-plugin-grey > eolinker_com_apinto_strategy-plugin-grey.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/strategy-plugin-fuse > eolinker_com_apinto_strategy-plugin-fuse.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/response_file_parse > eolinker_com_apinto_response_file_parse.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/ai_formatter > eolinker_com_apinto_ai_formatter.json
curl -s http://127.0.0.1:9400/extender/eolinker.com:apinto/ai_prompt > eolinker_com_apinto_ai_prompt.json