#!/usr/bin/env sh

# 获取当前分支名
BRANCH=$(git rev-parse --abbrev-ref HEAD)

# 如果是从 feature 分支推送
echo $BRANCH
if [[ $BRANCH == feature/* || $BRANCH == fix/* ]]; then
    # 获取远程仓库列表
    REMOTES=$(git remote)

    # 检查是否存在 gitlab 和 github 远程仓库
    if echo "$REMOTES" | grep -q "gitlab"; then
        echo "Pushing $BRANCH to GitLab..."
        git push gitlab $BRANCH
    fi

    # 只有在明确要求时才推送到 GitHub
    if echo "$REMOTES" | grep -q "github"; then
        echo "Pushing $BRANCH to GitHub..."
        git push github $BRANCH
    fi
fi
