#!/usr/bin/env sh

# 获取当前分支名
BRANCH=$(git rev-parse --abbrev-ref HEAD)

# 获取远程仓库列表
REMOTES=$(git remote)

# 检查是否存在 gitlab 远程仓库
if ! echo "$REMOTES" | grep -q "gitlab"; then
    echo "Error: GitLab remote repository not found"
    exit 1
fi

echo "Pushing $BRANCH to GitLab..."

# 如果存在 github 远程仓库，推送到 GitHub
if echo "$REMOTES" | grep -q "github"; then
    echo "Pushing $BRANCH to GitHub..."
    git push github $BRANCH
fi

git push gitlab $BRANCH
